name: GitHub Actions Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Log hello message
      run: |
        echo "Hello from @${{ github.actor }}"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        
    - name: Show Node.js info
      run: |
        echo "Node.js version:"
        node --version
        echo "npm version:"
        npm --version 